from app.predictor import predict_text
from pathlib import Path
import joblib
import numpy as np



BASE_DIR = Path(__file__).resolve().parent.parent
MODEL_DIR = BASE_DIR / "models"

vectorizer = joblib.load(MODEL_DIR / "vectorizer.pkl")
model = joblib.load(MODEL_DIR / "logreg.pkl")

def test_predict_text_output_shape():
    proba = predict_text(
        "This is a test sentence.",
        vectorizer,
        model
    )
    assert proba.shape == (2,)

<<<<<<< HEAD
def test_predict_text_output_shape():
    proba = predict_text(
        "This is a test sentence.",
        vectorizer,
        model
    )
    assert proba.shape == (2,)

=======
>>>>>>> 06746461549353012634c198f6b5c8fb8a12b308

def test_predict_text_probability_sum():
    proba = predict_text(
        "Human written academic paragraph.",
        vectorizer,
        model
    )
    assert np.isclose(proba.sum(), 1.0)
<<<<<<< HEAD

=======
    
>>>>>>> 06746461549353012634c198f6b5c8fb8a12b308
def test_vectorizer_output_shape():
    text = "This is a test sentence."
    X = vectorizer.transform([text])
    assert X.shape[0] == 1
    print("TEST 1 BAŞARILI: Vectorizer çıktısı doğru")


def test_model_probability_shape():
    text = "This text was generated by an AI model."
    X = vectorizer.transform([text])
    proba = model.predict_proba(X)
    assert proba.shape == (1, 2)
    print("TEST 2 BAŞARILI: Model olasılık boyutu doğru")


def test_probability_sum_equals_one():
    text = "Human written academic paragraph."
    X = vectorizer.transform([text])
    proba = model.predict_proba(X)[0]
    assert np.isclose(proba.sum(), 1.0)
    print("TEST 3 BAŞARILI: Olasılıkların toplamı 1")
