import joblib
import numpy as np

vectorizer = joblib.load(r"D:\Masaüstü\human_ai\models\vectorizer.pkl")
model = joblib.load(r"D:\Masaüstü\human_ai\models\logreg.pkl")


def test_vectorizer_output_shape():
    text = "This is a test sentence."
    X = vectorizer.transform([text])
    assert X.shape[0] == 1
    print("TEST 1 BAŞARILI: Vectorizer çıktısı doğru")


def test_model_probability_shape():
    text = "This text was generated by an AI model."
    X = vectorizer.transform([text])
    proba = model.predict_proba(X)
    assert proba.shape == (1, 2)
    print("TEST 2 BAŞARILI: Model olasılık boyutu doğru")


def test_probability_sum_equals_one():
    text = "Human written academic paragraph."
    X = vectorizer.transform([text])
    proba = model.predict_proba(X)[0]
    assert np.isclose(proba.sum(), 1.0)
    print("TEST 3 BAŞARILI: Olasılıkların toplamı 1")
